// resources/js/Components/ui/button/Button.vue
<script lang="ts" setup>
import type { HTMLAttributes } from 'vue'
import { Primitive, type PrimitiveProps } from 'radix-vue'
import { type ButtonVariants, buttonVariants, loadingSpinnerVariants } from '.'
import { cn } from '@/Utils/utils'
import LoadingSpinner from '@/Components/LoadingSpinner.vue'

interface Props extends PrimitiveProps {
  variant?: ButtonVariants['variant']
  size?: ButtonVariants['size']
  class?: HTMLAttributes['class']
  loading?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  as: 'button',
  variant: 'default',
  size: 'default',
  class: '',
  loading: false,
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="
      cn(
        buttonVariants({ variant, size: variant === 'link' ? 'link' : size }),
        props.class
      )
    "
    :disabled="loading"
  >
    <span
      :class="loading ? 'scale-100 opacity-100' : 'scale-50 opacity-0'"
      class="absolute inset-0 flex items-center justify-center transition-all duration-300 ease-in-out"
    >
      <LoadingSpinner :class="loadingSpinnerVariants({ variant })" />
    </span>

    <span
      :class="loading ? 'scale-95 opacity-0' : 'scale-100 opacity-100'"
      class="inline-flex transition-all duration-300 ease-out"
    >
      <slot />
    </span>
  </Primitive>
</template>

// resources/js/Components/UI/Button.tsx
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'
import * as React from 'react'

import { LoadingSpinner } from '@/Components/LoadingSpinner'
import { cn } from '@/Utils/utils'

const buttonVariants = cva(
  'inline-flex relative items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-foreground underline decoration-foreground/30 hover:decoration-foreground font-normal',
      },
      size: {
        default: 'h-10 px-4 py-2',
        xs: 'h-7 rounded px-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10',
        link: '',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
)

const loadingSpinnerVariants = cva('', {
  variants: {
    variant: {
      default: 'text-primary-foreground',
      destructive: 'text-destructive-foreground',
      outline: 'text-accent-foreground',
      secondary: 'text-secondary-foreground',
      ghost: 'text-accent-foreground',
      link: 'text-primary-foreground',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
})

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
  loading?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, loading = false, children, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button'
    return (
      <Comp
        className={cn(
          buttonVariants({ variant, size: variant === 'link' ? 'link' : size }),
          className
        )}
        ref={ref}
        disabled={loading}
        {...props}
      >
        <span
          className={cn(
            loading ? 'scale-100 opacity-100' : 'scale-50 opacity-0',
            'absolute inset-0 flex items-center justify-center transition-all duration-300 ease-in-out'
          )}
        >
          <LoadingSpinner className={loadingSpinnerVariants({ variant })} />
        </span>

        <span
          className={cn(
            loading ? 'scale-95 opacity-0' : 'scale-100 opacity-100',
            'inline-flex transition-all duration-300 ease-out'
          )}
        >
          {children}
        </span>
      </Comp>
    )
  }
)
Button.displayName = 'Button'

export { Button, buttonVariants }
