// resources/js/components/ui/skeleton.tsx
import { cn } from '@/utils/utils'
import * as React from 'react'

function Skeleton({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="skeleton"
      className={cn('bg-primary/10 animate-pulse rounded-md', className)}
      {...props}
    />
  )
}

export { Skeleton }

// resources/js/Components/ui/skeleton/Skeleton.vue
<script lang="ts" setup>
import type { HTMLAttributes } from 'vue'
import { cn } from '@/Utils/utils'

interface SkeletonProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<SkeletonProps>()
</script>

<template>
  <div :class="cn('animate-pulse rounded-md bg-muted', props.class)" />
</template>
