// resources/js/Pages/Account/Partials/AccountBreadcrumbs.tsx
import { type BreadcrumbItemType, PageBreadcrumbs } from '@/Components/PageBreadcrumbs'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export function AccountBreadcrumbs() {
  const { t } = useLaravelReactI18n()

  const items: BreadcrumbItemType[] = [
    {
      label: t('navigation.account_settings'),
      href: route('account.edit'),
    },
  ]

  switch (true) {
    case route().current('account.edit'):
      items.push({
        label: t('navigation.general'),
      })
      break

    case route().current('account.security.edit'):
      items.push({
        label: t('navigation.security'),
      })
      break

    case route().current('account.preferences.edit'):
      items.push({
        label: t('navigation.preferences'),
      })
      break
  }

  return <PageBreadcrumbs items={items} />
}

// resources/js/Pages/Account/Partials/AccountBreadcrumbs.vue
<script lang="ts" setup>
import PageBreadcrumbs, {
  type BreadcrumbItemType,
} from '@/Components/PageBreadcrumbs.vue'
import { computed } from 'vue'
import { trans } from 'laravel-vue-i18n'

const breadcrumbs = computed(() => {
  const items: BreadcrumbItemType[] = [
    {
      label: trans('navigation.account_settings'),
      href: route('account.edit'),
    },
  ]

  switch (true) {
    case route().current('account.edit'):
      items.push({
        label: trans('navigation.general'),
      })
      break

    case route().current('account.security.edit'):
      items.push({
        label: trans('navigation.security'),
      })
      break

    case route().current('account.preferences.edit'):
      items.push({
        label: trans('navigation.preferences'),
      })
      break
  }

  return items
})
</script>

<template>
  <PageBreadcrumbs :items="breadcrumbs" />
</template>
