// resources/js/Pages/Account/Partials/AccountNavigation.vue
<script lang="ts" setup>
import PageNavigation from '@/Components/PageNavigation.vue'
import { wTrans } from 'laravel-vue-i18n'

const navItems = [
  {
    label: wTrans('navigation.general'),
    href: route('account.edit'),
    current: route().current('account.edit'),
  },
  {
    label: wTrans('navigation.security'),
    href: route('account.security.edit'),
    current: route().current('account.security.edit'),
  },
  {
    label: wTrans('navigation.preferences'),
    href: route('account.preferences.edit'),
    current: route().current('account.preferences.edit'),
  },
]
</script>

<template>
  <PageNavigation :items="navItems" />
</template>

// resources/js/pages/account/partials/account-navigation.tsx
import { PageNavigation } from '@/components/page-navigation'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export function AccountNavigation() {
  const { t } = useLaravelReactI18n()

  const navItems = [
    {
      label: t('navigation.general'),
      href: route('account.edit'),
      current: route().current('account.edit'),
    },
    {
      label: t('navigation.security'),
      href: route('account.security.edit'),
      current: route().current('account.security.edit'),
    },
    {
      label: t('navigation.preferences'),
      href: route('account.preferences.edit'),
      current: route().current('account.preferences.edit'),
    },
  ]

  return <PageNavigation items={navItems} />
}
