// resources/js/pages/account/partials/avatar-form.tsx
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Skeleton } from '@/components/ui/skeleton'
import { useUser } from '@/contexts/user-context'
import { useFormValidation } from '@/hooks/use-form-validation'
import { initials } from '@/utils/strings'
import { cn } from '@/utils/utils'
import { zodResolver } from '@hookform/resolvers/zod'
import { router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'
import { ChangeEvent, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { z } from 'zod'

const formSchema = z.object({
  avatar: z.union([z.instanceof(File), z.literal('')]),
})

export function AvatarForm() {
  const { t } = useLaravelReactI18n()

  const { user } = useUser()

  const { setFormServerErrors } = useFormValidation()

  const [isRemovingAvatar, setIsRemovingAvatar] = useState(false)

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      avatar: new File([], ''),
    },
  })

  const inputRef = useRef<HTMLInputElement | null>(null)

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await new Promise<void>((resolve) =>
      router.post(
        route('account.avatar.update'),
        { ...values, _method: 'put' },
        {
          preserveScroll: true,
          onError: (errors) => {
            setFormServerErrors(form, errors)
          },
          onSuccess: () => {
            form.reset()

            toast.success(t('account.account_updated'), {
              description: t('account.account_has_been_updated'),
            })
          },
          onFinish: () => resolve(),
        }
      )
    )
  }

  async function handleRemoveAvatarClick() {
    await new Promise<void>((resolve) =>
      router.delete(route('account.avatar.destroy'), {
        preserveScroll: true,
        onStart: () => setIsRemovingAvatar(true),
        onSuccess: () => {
          toast.success(t('account.account_updated'), {
            description: t('account.account_has_been_updated'),
          })
        },
        onFinish: () => {
          setIsRemovingAvatar(false)
          resolve()
        },
      })
    )
  }

  function handleFileChange(e: ChangeEvent<HTMLInputElement>) {
    const files = e.target.files

    if (files?.length) {
      form.setValue('avatar', files[0], { shouldValidate: true })
      form.handleSubmit(onSubmit)()
    }
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <FormField
          control={form.control}
          name="avatar"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{t('general.avatar')}</FormLabel>
              <FormDescription>
                {t('account.avatar_description')}
              </FormDescription>
              <FormControl>
                <div className="flex items-center space-x-4">
                  <div className="size-11 shrink-0">
                    {form.formState.isSubmitting || isRemovingAvatar ? (
                      <Skeleton className="size-11 rounded-md" />
                    ) : (
                      <Avatar size="md">
                        {user.avatarUrl ? (
                          <>
                            <AvatarImage
                              alt={user.name}
                              src={user.avatarUrl}
                              className={cn({
                                'opacity-50':
                                  form.formState.isSubmitting ||
                                  isRemovingAvatar,
                              })}
                            />
                            <AvatarFallback delayMs={500}>
                              {initials(user.name)}
                            </AvatarFallback>
                          </>
                        ) : (
                          <span>{initials(user.name)}</span>
                        )}
                      </Avatar>
                    )}
                  </div>

                  <div>
                    <input
                      {...field}
                      value=""
                      accept="image/*"
                      className="hidden"
                      type="file"
                      ref={(e) => {
                        field.ref(e)
                        inputRef.current = e
                      }}
                      onChange={handleFileChange}
                    />

                    <div className="flex items-center space-x-2">
                      <Button
                        loading={form.formState.isSubmitting}
                        type="button"
                        variant="secondary"
                        onClick={() => inputRef.current?.click()}
                      >
                        {t('general.change')}
                      </Button>

                      <Button
                        disabled={!user.avatarUrl}
                        loading={isRemovingAvatar}
                        type="button"
                        variant="destructive"
                        onClick={handleRemoveAvatarClick}
                      >
                        {t('general.remove')}
                      </Button>
                    </div>
                  </div>
                </div>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </form>
    </Form>
  )
}

// resources/js/Pages/Account/Partials/AvatarForm.vue
<script lang="ts" setup>
import { useTemplateRef } from 'vue'
import { useUser } from '@/Composables/useUser'
import { initials } from '@/Utils/strings'
import { router } from '@inertiajs/vue3'
import { trans } from 'laravel-vue-i18n'
import { useToast } from '@/Components/ui/toast'
import { Avatar, AvatarFallback, AvatarImage } from '@/Components/ui/avatar'
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/ui/form'
import { Button } from '@/Components/ui/button'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { Form, GenericObject, SubmissionContext } from 'vee-validate'
import { Skeleton } from '@/Components/ui/skeleton'

const { user } = useUser()

const fileInput = useTemplateRef<HTMLInputElement>('fileInput')

const formSchema = toTypedSchema(
  z.object({
    avatar: z.instanceof(File).nullable().optional(),
  })
)

function openFileInput() {
  fileInput.value?.click()
}

async function submit(values: GenericObject, actions: SubmissionContext) {
  if (values.avatar === undefined) {
    return
  }

  await new Promise<void>((resolve) =>
    router.post(
      route('account.avatar.update'),
      { ...values, _method: 'put' },
      {
        preserveScroll: true,
        onError: (errors) => {
          actions.resetForm({ errors })
        },
        onSuccess: () => {
          actions.resetForm()

          useToast().toast({
            description: trans('account.account_has_been_updated'),
            title: trans('account.account_updated'),
            variant: 'successful',
          })
        },
        onFinish: () => resolve(),
      }
    )
  )
}
</script>

<template>
  <Form
    v-slot="{ isSubmitting, handleSubmit }"
    :validation-schema="formSchema"
    class="space-y-6"
    @submit="submit"
  >
    <FormField
      v-slot="{ handleChange, handleBlur, setValue }"
      name="avatar"
      @update:model-value="handleSubmit($event, submit)"
    >
      <FormItem>
        <FormLabel>
          {{ $t('general.avatar') }}
        </FormLabel>
        <FormDescription>
          {{ $t('account.avatar_description') }}
        </FormDescription>
        <FormControl>
          <div class="flex items-center space-x-4">
            <div class="size-11 shrink-0">
              <Skeleton v-if="isSubmitting" class="size-11 rounded-full" />

              <Avatar v-else size="md">
                <AvatarImage
                  v-if="user.avatar_url"
                  :alt="user.name"
                  :class="{ 'opacity-50': isSubmitting }"
                  :src="user.avatar_url"
                />
                <component
                  :is="user.avatar_url ? AvatarFallback : 'span'"
                  :delay-ms="user.avatar_url ? 500 : 0"
                >
                  {{ initials(user.name) }}
                </component>
              </Avatar>
            </div>

            <div>
              <input
                ref="fileInput"
                accept="image/*"
                class="hidden"
                type="file"
                @blur="handleBlur"
                @change="handleChange"
              />

              <div class="flex items-center space-x-2">
                <Button
                  :loading="isSubmitting && !user.avatar_url"
                  type="button"
                  variant="secondary"
                  @click="openFileInput"
                >
                  {{ $t('general.change') }}
                </Button>

                <Button
                  :disabled="!user.avatar_url"
                  :loading="isSubmitting && !!user.avatar_url"
                  type="button"
                  variant="destructive"
                  @click="setValue(null)"
                >
                  {{ $t('general.remove') }}
                </Button>
              </div>
            </div>
          </div>
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>
  </Form>
</template>
