// resources/js/Pages/Account/Partials/DeleteAccountForm.vue
<script lang="ts" setup>
import SettingsGrid from '@/Components/SettingsGrid.vue'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/ui/form'
import { Button } from '@/Components/ui/button'
import { Input } from '@/Components/ui/input'
import { router } from '@inertiajs/vue3'
import { GenericObject, SubmissionContext } from 'vee-validate'

const formSchema = toTypedSchema(
  z.object({
    password: z.string(),
  })
)

async function submit(
  values: GenericObject,
  actions: SubmissionContext
): Promise<void> {
  await new Promise<void>((resolve) =>
    router.delete(route('account.destroy'), {
      preserveScroll: true,
      data: values,
      onError: (errors) => {
        actions.resetForm({ values, errors })
      },
      onFinish: () => resolve(),
    })
  )
}
</script>

<template>
  <SettingsGrid
    :description="$t('account.delete_account_description')"
    :title="$t('account.delete_account')"
  >
    <Form
      v-slot="{ isSubmitting }"
      :validation-schema="formSchema"
      class="space-y-6"
      @submit="submit"
    >
      <FormField v-slot="{ componentField }" name="password">
        <FormItem>
          <FormLabel>
            {{ $t('general.password') }}
          </FormLabel>
          <FormControl>
            <Input
              autocomplete="current-password"
              required
              type="password"
              v-bind="componentField"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <Button :loading="isSubmitting" type="submit" variant="destructive">
        {{ $t('account.delete_account') }}
      </Button>
    </Form>
  </SettingsGrid>
</template>

// resources/js/pages/account/partials/delete-account-form.tsx
import { SettingsGrid } from '@/components/settings-grid'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { useFormValidation } from '@/hooks/use-form-validation'
import { zodResolver } from '@hookform/resolvers/zod'
import { router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

const formSchema = z.object({
  password: z.string(),
})

export function DeleteAccountForm() {
  const { t } = useLaravelReactI18n()

  const { setFormServerErrors } = useFormValidation()

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      password: '',
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await new Promise<void>((resolve) =>
      router.delete(route('account.destroy'), {
        preserveScroll: true,
        data: values,
        onError: (errors) => {
          setFormServerErrors(form, errors)
        },
        onFinish: () => resolve(),
      })
    )
  }

  return (
    <SettingsGrid
      description={t('account.delete_account_description')}
      title={t('account.delete_account')}
    >
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('general.password')}</FormLabel>
                <FormControl>
                  <Input autoComplete="current-password" required type="password" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button loading={form.formState.isSubmitting} variant="destructive" type="submit">
            {t('account.delete_account')}
          </Button>
        </form>
      </Form>
    </SettingsGrid>
  )
}
