// resources/js/Pages/Account/Partials/PasswordForm.vue
<script lang="ts" setup>
import SettingsGrid from '@/Components/SettingsGrid.vue'
import { trans } from 'laravel-vue-i18n'
import { Button } from '@/Components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/ui/form'
import { Input } from '@/Components/ui/input'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { router } from '@inertiajs/vue3'
import { useToast } from '@/Components/ui/toast'
import { GenericObject, SubmissionContext } from 'vee-validate'
import { passwordConfirmationMessage } from '@/Utils/zodValidation'

const formSchema = toTypedSchema(
  z
    .object({
      current_password: z.string(),
      password: z.string().min(8),
      password_confirmation: z.string().min(8),
    })
    .refine(
      (data) => data.password === data.password_confirmation,
      () => passwordConfirmationMessage()
    )
)

async function submit(
  values: GenericObject,
  actions: SubmissionContext
): Promise<void> {
  await new Promise<void>((resolve) =>
    router.put(route('account.password.update'), values, {
      preserveScroll: true,
      onError: (errors) => {
        actions.resetForm({ values, errors })
      },
      onSuccess: () => {
        actions.resetForm()

        useToast().toast({
          description: trans('account.account_has_been_updated'),
          title: trans('account.account_updated'),
          variant: 'successful',
        })
      },
      onFinish: () => resolve(),
    })
  )
}
</script>

<template>
  <SettingsGrid
    :description="$t('account.change_password_description')"
    :title="$t('account.change_password')"
  >
    <Form
      v-slot="{ isSubmitting }"
      :validation-schema="formSchema"
      class="space-y-6"
      @submit="submit"
    >
      <FormField v-slot="{ componentField }" name="current_password">
        <FormItem>
          <FormLabel>
            {{ $t('account.current_password') }}
          </FormLabel>
          <FormControl>
            <Input
              autocomplete="current-password"
              required
              type="password"
              v-bind="componentField"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField v-slot="{ componentField }" name="password">
        <FormItem>
          <FormLabel>
            {{ $t('account.new_password') }}
          </FormLabel>
          <FormControl>
            <Input
              autocomplete="new-password"
              required
              type="password"
              v-bind="componentField"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField v-slot="{ componentField }" name="password_confirmation">
        <FormItem>
          <FormLabel>
            {{ $t('account.confirm_new_password') }}
          </FormLabel>
          <FormControl>
            <Input
              autocomplete="new-password"
              required
              type="password"
              v-bind="componentField"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <Button :loading="isSubmitting" type="submit">
        {{ $t('account.update_password') }}
      </Button>
    </Form>
  </SettingsGrid>
</template>

// resources/js/pages/account/partials/password-form.tsx
import { SettingsGrid } from '@/components/settings-grid'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { useFormValidation } from '@/hooks/use-form-validation'
import { zodResolver } from '@hookform/resolvers/zod'
import { router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { z } from 'zod'

const formSchema = z.object({
  currentPassword: z.string(),
  password: z.string().min(8),
  passwordConfirmation: z.string().min(8),
})

export function PasswordForm() {
  const { t } = useLaravelReactI18n()

  const { setFormServerErrors, passwordConfirmationMessage } =
    useFormValidation()

  formSchema.refine(
    (data) => data.password === data.passwordConfirmation,
    () => passwordConfirmationMessage()
  )

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      currentPassword: '',
      password: '',
      passwordConfirmation: '',
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await new Promise<void>((resolve) =>
      router.put(route('account.password.update'), values, {
        preserveScroll: true,
        onError: (errors) => {
          setFormServerErrors(form, errors)
        },
        onSuccess: () => {
          form.reset()

          toast.success(t('account.account_updated'), {
            description: t('account.account_has_been_updated'),
          })
        },
        onFinish: () => resolve(),
      })
    )
  }

  return (
    <SettingsGrid
      description={t('account.change_password_description')}
      title={t('account.change_password')}
    >
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="mt-6 space-y-6">
          <FormField
            control={form.control}
            name="currentPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('account.current_password')}</FormLabel>
                <FormControl>
                  <Input
                    autoComplete="current-password"
                    required
                    type="password"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('account.new_password')}</FormLabel>
                <FormControl>
                  <Input
                    autoComplete="new-password"
                    required
                    type="password"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="passwordConfirmation"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('account.confirm_new_password')}</FormLabel>
                <FormControl>
                  <Input
                    autoComplete="new-password"
                    required
                    type="password"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button loading={form.formState.isSubmitting} type="submit">
            {t('account.update_password')}
          </Button>
        </form>
      </Form>
    </SettingsGrid>
  )
}
