// resources/js/Pages/Account/Partials/PreferencesForm.vue
<script lang="ts" setup>
import SettingsGrid from '@/Components/SettingsGrid.vue'
import { type Component, inject } from 'vue'
import { UseDarkMode } from '@/Types'
import { trans } from 'laravel-vue-i18n'
import { useLocale } from '@/Composables/useLocale'
import { getCountryFromLocale } from '@/Utils/locale'
import IconFlagGB from '@/Components/Icons/IconFlagGB.vue'
import { Globe } from 'lucide-vue-next'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/ui/form'
import { Button } from '@/Components/ui/button'
import { Switch } from '@/Components/ui/switch'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/Components/ui/select'
import { router } from '@inertiajs/vue3'
import { useToast } from '@/Components/ui/toast'
import { GenericObject, SubmissionContext } from 'vee-validate'
import IconFlagFR from '@/Components/Icons/IconFlagFR.vue'

const { supportedLocales, currentLocale } = useLocale()

const useDarkTheme = inject<UseDarkMode>('useDarkTheme')

const formSchema = toTypedSchema(
  z.object({
    language: z.string().default(currentLocale.value),
  })
)

const supportedLocaleOptions = Object.entries(supportedLocales.value).map(
  ([locale, data]) => ({
    value: locale,
    label: data.nativeName,
    icon: getCountryFlag(data.regional),
  })
)

function getCountryFlag(locale: string): Component | undefined {
  const country = getCountryFromLocale(locale)

  if (!country) {
    return Globe
  }

  switch (country) {
    case 'GB':
      return IconFlagGB
    case 'FR':
      return IconFlagFR
    default:
      return Globe
  }
}

async function submit(
  values: GenericObject,
  actions: SubmissionContext
): Promise<void> {
  await new Promise<void>((resolve) =>
    router.put(route('account.preferences.update'), values, {
      preserveScroll: true,
      onError: (errors) => {
        actions.resetForm({ values, errors })
      },
      onSuccess: () => {
        useToast().toast({
          description: trans('account.account_has_been_updated'),
          title: trans('account.account_updated'),
          variant: 'successful',
        })
      },
      onFinish: () => resolve(),
    })
  )
}
</script>

<template>
  <SettingsGrid
    :description="$t('account.preferences_description')"
    :title="$t('account.preferences')"
  >
    <Form>
      <FormField
        v-slot="{ value, handleChange }"
        v-model="useDarkTheme"
        name="theme"
      >
        <FormItem class="flex items-center justify-between space-x-4">
          <div class="space-y-2">
            <FormLabel>
              {{ $t('account.use_dark_mode') }}
            </FormLabel>
            <FormDescription>
              {{ $t('account.use_dark_mode_description') }}
            </FormDescription>
          </div>

          <FormControl>
            <Switch :checked="value" @update:checked="handleChange" />
          </FormControl>
        </FormItem>
      </FormField>
    </Form>

    <Form
      v-slot="{ isSubmitting }"
      :validation-schema="formSchema"
      class="mt-6 space-y-6"
      @submit="submit"
    >
      <FormField v-slot="{ componentField }" name="language">
        <FormItem>
          <FormLabel>
            {{ $t('general.language') }}
          </FormLabel>
          <Select v-bind="componentField">
            <FormControl>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
            </FormControl>
            <SelectContent>
              <SelectGroup>
                <SelectItem
                  v-for="option in supportedLocaleOptions"
                  :key="option.value"
                  :value="option.value"
                >
                  <span class="flex items-center gap-2 truncate">
                    <component
                      :is="option.icon"
                      class="h-3 w-auto shrink-0 text-muted-foreground"
                    />

                    {{ option.label }}
                  </span>
                </SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <FormDescription>
            {{ $t('account.select_your_language') }}
          </FormDescription>
          <FormMessage />
        </FormItem>
      </FormField>

      <Button :loading="isSubmitting" type="submit">
        {{ $t('account.update_preferences') }}
      </Button>
    </Form>
  </SettingsGrid>
</template>

// resources/js/Pages/Account/Partials/PreferencesForm.tsx
import { IconFlagFR } from '@/Components/Icons/IconFlagFR'
import { IconFlagGB } from '@/Components/Icons/IconFlagGB'
import { useDarkMode } from '@/Components/Providers/DarkModeProvider'
import { SettingsGrid } from '@/Components/SettingsGrid'
import { Button } from '@/Components/UI/Button'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/UI/Form'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/Components/UI/Select'
import { Switch } from '@/Components/UI/Switch'
import { useFormValidation } from '@/Hooks/useFormValidation'
import { useLocale } from '@/Hooks/useLocale'
import { useToast } from '@/Hooks/useToast'
import { zodResolver } from '@hookform/resolvers/zod'
import { router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'
import { Globe } from 'lucide-react'
import { ElementType } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

const formSchema = z.object({
  language: z.string(),
})

export function DarkModeForm() {
  const { t } = useLaravelReactI18n()

  const { isDarkMode, setDarkMode } = useDarkMode()

  const form = useForm({
    defaultValues: {
      use_dark_mode: isDarkMode,
    },
  })

  function handleDarkModeChange(useDarkMode: boolean) {
    setDarkMode(useDarkMode)
  }

  return (
    <Form {...form}>
      <form className="mt-6 space-y-6">
        <FormField
          control={form.control}
          name="use_dark_mode"
          render={({ field }) => (
            <FormItem className="flex justify-between space-x-4">
              <div className="space-y-2">
                <FormLabel>{t('account.use_dark_mode')}</FormLabel>
                <FormDescription>{t('account.use_dark_mode_description')}</FormDescription>
              </div>

              <FormControl>
                <Switch
                  checked={isDarkMode}
                  onCheckedChange={(e) => {
                    field.onChange(e)
                    handleDarkModeChange(e)
                  }}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </form>
    </Form>
  )
}

export function PreferencesForm() {
  const { t } = useLaravelReactI18n()

  const { toast } = useToast()

  const { setFormServerErrors } = useFormValidation()

  const { supportedLocales, currentLocale, getCountryFromLocale } = useLocale()

  const supportedLocaleOptions = Object.entries(supportedLocales).map(([locale, data]) => ({
    value: locale,
    label: data.nativeName,
    icon: getCountryFlag(data.regional),
  }))

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      language: currentLocale,
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await new Promise<void>((resolve) =>
      router.put(route('account.preferences.update'), values, {
        preserveScroll: true,
        onError: (errors) => {
          setFormServerErrors(form, errors)
        },
        onSuccess: () => {
          toast({
            description: t('account.account_has_been_updated'),
            title: t('account.account_updated'),
            variant: 'successful',
          })
        },
        onFinish: () => resolve(),
      })
    )
  }

  function getCountryFlag(locale: string): ElementType {
    const country = getCountryFromLocale(locale)

    if (!country) {
      return Globe
    }

    switch (country) {
      case 'GB':
        return IconFlagGB
      case 'FR':
        return IconFlagFR
      default:
        return Globe
    }
  }

  return (
    <SettingsGrid
      description={t('account.preferences_description')}
      title={t('account.preferences')}
    >
      <DarkModeForm />

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="mt-6 space-y-6">
          <FormField
            control={form.control}
            name="language"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('general.language')}</FormLabel>
                <FormControl>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {supportedLocaleOptions.map((option) => (
                        <SelectItem key={option.value} value={option.value}>
                          <span className="flex items-center gap-2 truncate">
                            <option.icon className="h-3 w-auto shrink-0 text-muted-foreground" />
                            {option.label}
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormControl>
                <FormDescription>{t('account.select_your_language')}</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button loading={form.formState.isSubmitting} type="submit">
            {t('account.update_preferences')}
          </Button>
        </form>
      </Form>
    </SettingsGrid>
  )
}
