// resources/js/pages/home.tsx
import { PageHeader } from '@/components/page-header'
import { Text } from '@/components/text'
import { AuthenticatedLayout } from '@/layouts/authenticated-layout'
import { Head } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export default function Home() {
  const { t } = useLaravelReactI18n()

  return (
    <AuthenticatedLayout>
      <Head title={t('general.home')} />

      <PageHeader>{t('general.home')}</PageHeader>

      <div className="py-10">
        <Text size="sm" variant="muted">
          Ipsum ipsa aliquam deserunt molestias incidunt optio. Labore aperiam consequuntur natus
          sit repudiandae accusantium illum doloribus omnis.
        </Text>
      </div>
    </AuthenticatedLayout>
  )
}

// resources/js/Pages/Home.vue
<script lang="ts" setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'
import { Head } from '@inertiajs/vue3'
import { Text } from '@/Components/ui/text'
import PageHeader from '@/Components/PageHeader.vue'
import PageBreadcrumbs from '@/Components/PageBreadcrumbs.vue'
</script>

<template>
  <Head :title="$t('general.home')" />

  <AuthenticatedLayout>
    <template #breadcrumbs>
      <PageBreadcrumbs />
    </template>

    <template #default>
      <PageHeader>
        {{ $t('general.home') }}
      </PageHeader>

      <div class="py-10">
        <Text size="sm" variant="muted">
          Ipsum ipsa aliquam deserunt molestias incidunt optio. Labore aperiam
          consequuntur natus sit repudiandae accusantium illum doloribus omnis.
        </Text>
      </div>
    </template>
  </AuthenticatedLayout>
</template>
