// resources/js/pages/account/general.tsx
import { PageHeader } from '@/components/page-header'
import { AuthenticatedLayout } from '@/layouts/authenticated-layout'
import { AccountBreadcrumbs } from '@/pages/account/partials/account-breadcrumbs'
import { AccountNavigation } from '@/pages/account/partials/account-navigation'
import { BasicInformationForm } from '@/pages/account/partials/basic-information-form'
import { DeleteAccountForm } from '@/pages/account/partials/delete-account-form'
import { Head } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export default function General() {
  const { t } = useLaravelReactI18n()

  return (
    <AuthenticatedLayout breadcrumbs={AccountBreadcrumbs}>
      <Head title={t('account.account_settings')} />

      <PageHeader>{t('account.account_settings')}</PageHeader>

      <AccountNavigation />

      <div className="divide-border divide-y">
        <BasicInformationForm />
        <DeleteAccountForm />
      </div>
    </AuthenticatedLayout>
  )
}

// resources/js/Pages/Account/General.vue
<script lang="ts" setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'
import { Head } from '@inertiajs/vue3'
import BasicInformationForm from '@/Pages/Account/Partials/BasicInformationForm.vue'
import DeleteAccountForm from '@/Pages/Account/Partials/DeleteAccountForm.vue'
import PageHeader from '@/Components/PageHeader.vue'
import AccountBreadcrumbs from '@/Pages/Account/Partials/AccountBreadcrumbs.vue'
import AccountNavigation from '@/Pages/Account/Partials/AccountNavigation.vue'
</script>

<template>
  <Head :title="$t('account.account_settings')" />

  <AuthenticatedLayout>
    <template #breadcrumbs>
      <AccountBreadcrumbs />
    </template>

    <template #default>
      <PageHeader>
        {{ $t('account.account_settings') }}
      </PageHeader>

      <AccountNavigation />

      <div class="divide-y divide-border">
        <BasicInformationForm />
        <DeleteAccountForm />
      </div>
    </template>
  </AuthenticatedLayout>
</template>
