// resources/js/pages/account/preferences.tsx
import { PageHeader } from '@/components/page-header'
import { AuthenticatedLayout } from '@/layouts/authenticated-layout'
import { AccountBreadcrumbs } from '@/pages/account/partials/account-breadcrumbs'
import { AccountNavigation } from '@/pages/account/partials/account-navigation'
import { PreferencesForm } from '@/pages/account/partials/preferences-form'
import { Head } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export default function Preferences() {
  const { t } = useLaravelReactI18n()

  return (
    <AuthenticatedLayout breadcrumbs={AccountBreadcrumbs}>
      <Head title={t('account.account_preferences')} />

      <PageHeader>{t('account.account_settings')}</PageHeader>

      <AccountNavigation />

      <div className="divide-border divide-y">
        <PreferencesForm />
      </div>
    </AuthenticatedLayout>
  )
}

// resources/js/Pages/Account/Preferences.vue
<script lang="ts" setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'
import { Head } from '@inertiajs/vue3'
import PreferencesForm from '@/Pages/Account/Partials/PreferencesForm.vue'
import PageHeader from '@/Components/PageHeader.vue'
import AccountBreadcrumbs from '@/Pages/Account/Partials/AccountBreadcrumbs.vue'
import AccountNavigation from '@/Pages/Account/Partials/AccountNavigation.vue'
</script>

<template>
  <Head :title="$t('account.account_preferences')" />

  <AuthenticatedLayout>
    <template #breadcrumbs>
      <AccountBreadcrumbs />
    </template>

    <template #default>
      <PageHeader>
        {{ $t('account.account_settings') }}
      </PageHeader>

      <AccountNavigation />

      <div class="divide-y divide-border">
        <PreferencesForm />
      </div>
    </template>
  </AuthenticatedLayout>
</template>
