// resources/js/Components/AuthForm.vue
<script lang="ts" setup>
import { Heading } from '@/Components/ui/heading'
import { Text } from '@/Components/ui/text'

defineProps<{
  title: string
  description: string
}>()
</script>

<template>
  <div class="w-full space-y-10 sm:max-w-sm">
    <div class="space-y-2">
      <Heading>
        {{ title }}
      </Heading>
      <Text size="sm" variant="muted">
        {{ description }}
      </Text>
    </div>

    <slot />

    <div v-if="$slots.footer">
      <slot name="footer" />
    </div>
  </div>
</template>

// resources/js/components/auth-form.tsx
import { Heading } from '@/components/heading'
import { Text } from '@/components/text'
import { PropsWithChildren } from 'react'

export function AuthFormFooter({ children }: PropsWithChildren) {
  return <div>{children}</div>
}

export function AuthForm({
  title,
  description,
  children,
}: PropsWithChildren<{
  title: string
  description: string
}>) {
  return (
    <div className="w-full space-y-10 sm:max-w-sm">
      <div className="space-y-2">
        <Heading>{title}</Heading>
        <Text size="sm" variant="muted">
          {description}
        </Text>
      </div>

      {children}
    </div>
  )
}
