// resources/js/Components/ui/text/Text.vue
<script lang="ts" setup>
import { Primitive, type PrimitiveProps } from 'radix-vue'
import type { HTMLAttributes } from 'vue'
import { cn } from '@/Utils/utils'
import { TextVariants, textVariants } from '@/Components/ui/text/index'

interface Props extends PrimitiveProps {
  variant?: TextVariants['variant']
  size?: TextVariants['size']
  weight?: TextVariants['weight']
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  as: 'span',
  size: 'base',
  weight: 'normal',
  class: '',
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="cn(textVariants({ variant, size, weight }), props.class)"
  >
    <slot />
  </Primitive>
</template>

// resources/js/Components/Text.tsx
import { cn } from '@/Utils/utils'
import { Slot } from '@radix-ui/react-slot'
import { cva, VariantProps } from 'class-variance-authority'
import { ElementType, PropsWithChildren } from 'react'

const textVariants = cva('', {
  variants: {
    variant: {
      default: 'text-foreground',
      muted: 'text-muted-foreground',
    },
    size: {
      xs: 'text-xs',
      sm: 'text-sm',
      base: 'text-base',
      lg: 'text-lg',
    },
    weight: {
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
    },
  },
  defaultVariants: {
    variant: 'default',
    size: 'base',
    weight: 'normal',
  },
})

interface TextProps extends PropsWithChildren<VariantProps<typeof textVariants>> {
  as?: ElementType
  asChild?: boolean
  className?: string
}

export function Text({
  as = 'span',
  asChild = false,
  variant,
  size,
  weight,
  className,
  ...props
}: TextProps) {
  const Component = asChild ? Slot : as

  return <Component className={cn(textVariants({ variant, size, weight }), className)} {...props} />
}
