// resources/js/pages/auth/forgot-password.tsx
import { AuthForm, AuthFormFooter } from '@/components/auth-form'
import { Text } from '@/components/text'
import { TextLink } from '@/components/text-link'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { useFormValidation } from '@/hooks/use-form-validation'
import { GuestLayout } from '@/layouts/guest-layout'
import { zodResolver } from '@hookform/resolvers/zod'
import { Head, router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { z } from 'zod'

const formSchema = z.object({
  email: z.string().email(),
})

export default function ForgotPassword({ status }: { status?: string }) {
  const { t } = useLaravelReactI18n()

  const { setFormServerErrors } = useFormValidation()

  useEffect(() => {
    if (status === 'reset-link-sent') {
      toast.success(t('auth.password_reset_email_sent'), {
        description: t('auth.password_reset_email_sent_description'),
      })
    }
  }, [status, t])

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: '',
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    await new Promise<void>((resolve) =>
      router.post(route('password.email'), values, {
        onError: (errors) => {
          setFormServerErrors(form, errors)
        },
        onFinish: () => resolve(),
      })
    )
  }

  return (
    <GuestLayout>
      <Head title={t('auth.forgot_your_password')} />

      <AuthForm
        description={t('auth.forgot_your_password_description')}
        title={t('auth.forgot_your_password')}
      >
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('general.email')}</FormLabel>
                  <FormControl>
                    <Input
                      autoComplete="username"
                      inputMode="email"
                      required
                      type="email"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button loading={form.formState.isSubmitting} className="w-full" type="submit">
              {t('auth.send_password_reset_email')}
            </Button>
          </form>
        </Form>

        <AuthFormFooter>
          <Text as="p" size="sm" variant="muted">
            {t('auth.remembered_password') + ' '}

            <TextLink href={route('login')}>{t('auth.log_in')}</TextLink>
          </Text>
        </AuthFormFooter>
      </AuthForm>
    </GuestLayout>
  )
}

// resources/js/Pages/Auth/ForgotPassword.vue
<script lang="ts" setup>
import GuestLayout from '@/Layouts/GuestLayout.vue'
import { Head, router } from '@inertiajs/vue3'
import { onMounted } from 'vue'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { useToast } from '@/Components/ui/toast'
import { trans } from 'laravel-vue-i18n'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/Components/ui/form'
import { Input } from '@/Components/ui/input'
import { Text } from '@/Components/ui/text'
import { Button } from '@/Components/ui/button'
import { TextLink } from '@/Components/ui/text-link'
import AuthForm from '@/Components/AuthForm.vue'
import { GenericObject, SubmissionContext } from 'vee-validate'

const props = defineProps<{
  status?: string
}>()

const formSchema = toTypedSchema(
  z.object({
    email: z.string().email(),
  })
)

onMounted(() => {
  if (props.status === 'reset-link-sent') {
    showSuccessToast()
  }
})

async function submit(
  values: GenericObject,
  actions: SubmissionContext
): Promise<void> {
  await new Promise<void>((resolve) =>
    router.post(route('password.email'), values, {
      onError: (errors) => {
        actions.resetForm({ values, errors })
      },
      onSuccess: () => {
        actions.resetForm()
        showSuccessToast()
      },
      onFinish: () => resolve(),
    })
  )
}

function showSuccessToast() {
  useToast().toast({
    description: trans('auth.password_reset_email_sent_description'),
    title: trans('auth.password_reset_email_sent'),
    variant: 'successful',
  })
}
</script>

<template>
  <GuestLayout>
    <Head :title="$t('auth.forgot_your_password')" />

    <AuthForm
      :description="$t('auth.forgot_your_password_description')"
      :title="$t('auth.forgot_your_password')"
    >
      <template #default>
        <Form
          v-slot="{ isSubmitting }"
          :validation-schema="formSchema"
          class="space-y-6"
          @submit="submit"
        >
          <FormField v-slot="{ componentField }" name="email">
            <FormItem>
              <FormLabel>
                {{ $t('general.email') }}
              </FormLabel>
              <FormControl>
                <Input
                  autocomplete="username"
                  inputmode="email"
                  required
                  type="email"
                  v-bind="componentField"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          </FormField>

          <Button :loading="isSubmitting" class="w-full" type="submit">
            {{ $t('auth.send_password_reset_email') }}
          </Button>
        </Form>
      </template>

      <template #footer>
        <Text as="p" size="sm" variant="muted">
          {{ $t('auth.remembered_password') }}
          <TextLink :href="route('login')">
            {{ $t('auth.log_in') }}
          </TextLink>
        </Text>
      </template>
    </AuthForm>
  </GuestLayout>
</template>
