// resources/js/Pages/Auth/VerifyEmail.vue
<script lang="ts" setup>
import { watch } from 'vue'
import GuestLayout from '@/Layouts/GuestLayout.vue'
import { Head, router } from '@inertiajs/vue3'
import { useUser } from '@/Composables/useUser'
import AuthForm from '@/Components/AuthForm.vue'
import { Button } from '@/Components/ui/button'
import { Text } from '@/Components/ui/text'
import { useToast } from '@/Components/ui/toast'
import { trans } from 'laravel-vue-i18n'

const props = defineProps<{
  status?: string
}>()

const { user } = useUser()

watch(props, () => {
  if (props.status === 'verification-link-sent') {
    useToast().toast({
      description: trans('auth.email_verification_email_sent_description'),
      title: trans('auth.email_verification_email_sent'),
      variant: 'successful',
    })
  }
})

function resendEmail() {
  router.post(route('verification.send'))
}

function logout() {
  router.post(route('logout'))
}
</script>

<template>
  <GuestLayout>
    <Head :title="$t('auth.verify_email')" />

    <AuthForm
      :description="$t('auth.verify_email_description')"
      :title="$t('auth.verify_email')"
    >
      <template #default>
        <div class="flex flex-col items-center gap-4 sm:flex-row-reverse">
          <Button class="w-full" @click="resendEmail">
            {{ $t('auth.resend_email') }}
          </Button>

          <Button class="w-full" variant="secondary" @click="logout">
            {{ $t('auth.log_out') }}
          </Button>
        </div>
      </template>

      <template #footer>
        <Text as="p" size="xs" variant="muted">
          {{ $t('auth.email_delivered_to', { email: user.email }) }}
        </Text>
      </template>
    </AuthForm>
  </GuestLayout>
</template>

// resources/js/Pages/Auth/VerifyEmail.tsx
import { AuthForm, AuthFormFooter } from '@/Components/AuthForm'
import { Text } from '@/Components/Text'
import { Button } from '@/Components/UI/Button'
import { useToast } from '@/Hooks/useToast'
import { useUser } from '@/Hooks/useUser'
import { GuestLayout } from '@/Layouts/GuestLayout'
import { Head, router } from '@inertiajs/react'
import { useLaravelReactI18n } from 'laravel-react-i18n'

export default function VerifyEmail() {
  const { t } = useLaravelReactI18n()

  const { toast } = useToast()

  const { user } = useUser()

  function showEmailVerificationSentToast() {
    toast({
      description: t('auth.email_verification_email_sent_description'),
      title: t('auth.email_verification_email_sent'),
      variant: 'successful',
    })
  }

  function handleResendEmailClick() {
    router.post(route('verification.send'), undefined, {
      onSuccess: () => {
        showEmailVerificationSentToast()
      },
    })
  }

  function handleLogoutClick() {
    router.post(route('logout'))
  }

  return (
    <GuestLayout>
      <Head title={t('auth.verify_email')} />

      <AuthForm description={t('auth.verify_email_description')} title={t('auth.verify_email')}>
        <div className="flex flex-col items-center gap-4 sm:flex-row-reverse">
          <Button className="w-full" onClick={handleResendEmailClick}>
            {t('auth.resend_email')}
          </Button>

          <Button className="w-full" variant="secondary" onClick={handleLogoutClick}>
            {t('auth.log_out')}
          </Button>
        </div>

        <AuthFormFooter>
          <Text as="p" size="sm" variant="muted">
            {t('auth.email_delivered_to', { email: user.email })}
          </Text>
        </AuthFormFooter>
      </AuthForm>
    </GuestLayout>
  )
}
